config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'categories/index'
  authenticated :user do
    resources :categories do
      resources :purchases
    end
  end
  # Defines the root path route ("/")
  root "splash#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :purchase_categories
  has_many :purchases, through: :purchase_categories

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  has_many :purchase_categories
  has_many :categories, through: :purchase_categories

  validates :name, presence: true
  validates :amount, presence: true

  default_scope { order(created_at: :desc) }
end

app/models/purchase_category.rb
class PurchaseCategory < ApplicationRecord
  belongs_to :purchase
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :purchases

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  helper_method :current_user

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show destroy]

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      handle_uploaded_icon_file if category_params[:icon].present?
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.find(params[:id])
    @transactions = @category.purchases.order(created_at: :desc)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def handle_uploaded_icon_file
    uploaded_file = category_params[:icon]
    file_path = Rails.root.join('public', 'uploads', uploaded_file.original_filename)

    File.binwrite(file_path, uploaded_file.read)

    @category.update(icon: File.join('/uploads', uploaded_file.original_filename))
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: %i[show edit update destroy]

  def index
    @category = Category.find(params[:category_id])
    @purchases = current_user.purchases.order(created_at: :desc)
  end

  def show
    @purchase = Purchase.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @categories = current_user.categories
    @purchase = Purchase.new
    @selected_category_ids = []
  end

  def create
    primary_category_id = params[:purchase][:primary_category_id]
    additional_category_ids = params[:additional_category_ids] || []

    name = params[:purchase][:name]
    amount = params[:purchase][:amount]

    @purchase = Purchase.new(name:, amount:, user: current_user)

    if @purchase.save
      PurchaseCategory.create(purchase_id: @purchase.id, category_id: primary_category_id)

      additional_category_ids.each do |category_id|
        next if category_id.blank?

        PurchaseCategory.create(purchase_id: @purchase.id, category_id:)
      end

      redirect_to category_path(primary_category_id), notice: 'Purchase was successfully created.'
    else
      @categories = current_user.categories
      render :new
    end
  end

  def edit; end

  def update
    if @purchase.update(purchase_params)
      @purchase.category_ids = params[:purchase][:category_ids]
      redirect_to @purchase, notice: 'Purchase was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @purchase.destroy
    redirect_to purchases_url, notice: 'Purchase was successfully destroyed.'
  end

  private

  def set_purchase
    @purchase = Purchase.find(params[:id])
  end

  def purchase_params
    params.require(:purchase).permit(:name, :amount, :user_id, category_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= image_tag category.icon if category.icon.attached? %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_for @category, html: { multipart: true } do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="flex flex-col h-screen justify-between">

<div class="navigation">
  <ul class="flex justify-between p-4 blue-btn items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %></li>
    <h2>CATEGORIES</h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>

<div>
  <% @categories.each do |category| %>
    <%= link_to category do %>
      <div class="w-full p-3 rounded flex justify-between card-item">
        <div class="category-left">
          <% if category.icon.present? %>
          <div class="card-img"><%= image_tag category.icon, alt: category.name, class: 'category-icon' %></div>
          <% end %>
          </div>
          <div class="category-center">
          <h3><%= category.name %></h3>
          <p><%= category.created_at %></p>
        </div>
        <p>$ <%= category.purchases.sum(:amount) %></p>
      </div>
    <% end %>
  <% end %>
</div>

  <div class="text-center mt-4">
    <%= link_to new_category_path do %>
      <div class="w-full green-btn flex">
        <button class="p-2 py-4 m-4 text-lg w-full border-2 green-btn rounded hover:bg-green-600 focus:outline-none focus:bg-green-600">
            ADD A NEW CATEGORY
        </button>
      </div>
    <% end %>
  </div>

</div>

app/views/categories/new.html.erb
<div class="navigation blue-nav-white-text">
  <ul class="flex justify-between items-center blue-btn w-full p-4">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), categories_path, class: 'nav-link' %></li>
    <h2>NEW CATEGORY</h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>
<% if @category.errors.any? %>
  <div id="error_explanation", style="color: red">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
    <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="form-class flex flex-col justify-center">
<%= form_with(model: @category, url: categories_path, method: :post, multipart: true, class: 'mt-10 flex flex-col gap-y-10 form-category') do |form| %>
      <%= form.text_field :name, placeholder: "Enter Category Name", style: "display: block" %>
      <%= form.file_field :icon, id: 'icon_upload', style: "display: block" %>
      <%= form.submit "CREATE CATEGORY", class: 'p-2 py-4 m-4 text-lg w-full border-2 green-btn rounded hover:bg-green-600 focus:outline-none focus:bg-green-600 create-category-btn'%>
<% end %>
</div>

app/views/categories/show.html.erb
<div class="full-page">
<div class="navigation">
  <ul class="flex justify-between blue-btn p-4 items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), categories_path, class: 'nav-link' %></li>
    <h2>TRANSACTIONS</h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>
<div class="category-purchase">
<div class="category-purchase-container">
  <div class="category-header"> 
    <p><%= @category.name %></p>
    <p>Total Amount: $<%= @category.purchases.sum(:amount) %></p>
  </div>
  <div class="purchases-container flex flex-col">
  <% @category.purchases.each do |purchase| %>
    <div class="transaction-link">
       <%= link_to purchase.name, category_purchase_path(@category, purchase), class:'purchase-name' %>
        <p class="purchase-amount">$<%= purchase.amount %></p>
    </div>
  <% end %>
</div>

</div>

  <div class="text-center mt-4">
    <%= link_to new_category_purchase_path(@category) do %>
      <div class="w-full green-btn flex">
        <button class="p-2 py-4 m-4 text-lg w-full border-2 green-btn rounded hover:bg-green-600 focus:outline-none focus:bg-green-600 create-category-btn">
          ADD A NEW PURCHASE
        </button>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetBee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application.tailwind', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'wind', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/purchases/_form.html.erb
<%= form_with(model: purchase) do |form| %>
  <% if purchase.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/purchases/_purchase.html.erb
<div id="<%= dom_id purchase %>">
  <p>
    <strong>Name:</strong>
    <%= purchase.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= purchase.amount %>
  </p>

</div>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<div class="navigation">
  <ul class="flex justify-between blue-btn items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), category_path(params[:category_id]), class: 'nav-link' %></li>
    <h2>Purchases</h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>

<div class="purchases-container">
  <div>    
    <% @purchases.each do |purchase| %>
      <div class="purchase-item card-item">
        <%= link_to purchase.name, category_purchase_path(@category, purchase) %>
        $ <%= purchase.amount %>
      </div>
    <% end %>
  </div>
  <div class="flex links flex-col text-center">
      <%= link_to "Add a New Purchase", new_category_purchase_path(@category), class: "green-btn" %>
      <%= link_to "Categories", categories_path , class: "categories-btn" %>
  </div>
</div>

app/views/purchases/new.html.erb
<div class="navigation">
  <ul class="flex justify-between p-4 blue-btn items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), category_path(params[:category_id]), class: 'nav-link' %></li>
    <li><h2>PURCHASE</h2></li>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %></li>
  </ul>
</div>

<div>

  <div class="form-class flex flex-col justify-center">
  <%= form_with(model: [@category, @purchase], url: category_purchases_path(@category), method: :post, id: 'purchase-form') do |form| %> 
  <%= form.text_field :name, class: 'form-control', placeholder: 'Enter Name for Transaction' %>
  <%= form.text_field :amount, class: 'form-control', placeholder: 'Enter Amount for Transaction' %>
  <%= form.hidden_field :primary_category_id, value: @category.id %>
  <div class="mb-4">
    <%= select_tag "category", options_for_select(@categories.map { |category| [category.name, category.id] }), prompt: "Choose a category", class: "form-select" %>
  </div>
  <%= form.submit 'CREATE PURCHASE', class: 'p-2 py-4 m-4 text-lg w-full border-2 green-btn rounded hover:bg-green-600 focus:outline-none focus:bg-green-600 create-purchase-btn' %>
  <% end %>
  </div>

  <div class="back-to-purchase-container">
    <%= link_to "Back to purchases", category_purchases_path, class: "back-to-purchase" %>
  </div>
</div>

app/views/purchases/show.html.erb
<div class="navigation">
  <ul class="flex justify-between p-4 blue-btn items-center">
    <li class="w-10"><%= link_to image_tag('backarrow.png', alt: 'Back'), category_path(params[:category_id]), class: 'nav-link' %></li>
    <h2>TRANSACTION</h2>
    <li><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %></li>
  </ul>
</div>
<div class="transaction-container card-item text-center">
  <div class="transaction-heading">
    <p><%= @purchase.name %></p>
    <p><strong>Amount:</strong> <%= @purchase.amount %></p>
  </div>
  <div class="transaction-details">
  <h2>Categories:</h2>
  <ul>
    <% @purchase.categories.each do |category| %>
      <li><%= category.name %></li>
    <% end %>
  </ul>
    <p><strong>Created At:</strong> <%= @purchase.created_at.strftime('%B %d, %Y %I:%M %p') %></p>
  </div>
</div>

app/views/splash/index.html.erb
<div class="flex flex-col justify-between h-screen items-center">
<h1 class="text-center p-4 blue-btn w-full" >Budget Bee</h1>
<p>Track your expenses</p>
 <% if user_signed_in? %>

  <div class="w-full green-btn flex"> <!-- Set width to full and remove padding and margin -->
    <button class="p-2 py-4 m-4 text-lg w-full border-2 green-btn rounded hover:bg-green-600 focus:outline-none focus:bg-green-600 new-category-btn">
      <%= link_to 'ADD A NEW CATEGORY', new_category_path %>
    </button>
  </div>
<% else %>
  <div class="flex w-full items-center">
  <a href="/users/sign_in">
    <button class="blue-btn w-full p-4 border-e-2"><%= link_to 'Login', new_user_session_path %></button>
  </a href="/users/sign_out">
    <button class="blue-btn w-full p-4 border-s-2"><%= link_to 'Sign Up', new_user_registration_path %></button>
  </div>
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>